language: cpp

addons:
  apt:
    packages:
      - g++-9
      - cmake
      - cmake-data

jobs:
  include:
    # Unit Tests
    - stage: "Test"
      name: "Unit Tests"
      os: linux
      dist: focal
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
        - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
        - make
        - make test
    # Coverage Tests
    - stage: "Coverage"
      name: "Coverage Test"
      os: linux
      dist: focal
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
        - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" -DCMAKE_CXX_FLAGS=--coverage ..
        - make
        - make test
        - ./mst ../data/rmat0406.gr ../data/rmat0406.extra /dev/null
        - ./mst ../data/rmat0406.gr not-exists /dev/null 2>&1 | grep "Cannot open file" || false
        - touch restricted-file && chmod 400 restricted-file
        - ./mst ../data/rmat0406.gr ../data/rmat0406.extra restricted-file 2>&1 | grep "Cannot open file" || false
        - ./mst 2>&1 | grep Usage || false
        - ./test/test_mst-PRIM 2>&1 | grep Usage || false
        - ./test/test_mst-PRIM ../data/rmat0406.gr not-exists ../test/results/rmat0406.out 2>&1 | grep "Cannot open file" || false
        - ./test/test_mst-PRIM ../data/rmat0406.gr ../data/rmat0406.extra not-exists 2>&1 | grep "Cannot open file" || false
        - ./test/test_mst-PRIM not-exist ../data/rmat0406.extra ../test/results/rmat0406.out 2>&1 | grep "Cannot open file" || false
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    # Deploy
    - stage: "Deploy"
      name: "Generate Docs"
      branches:
        only:
          - master
      os: linux
      language: python
      python: "3.8"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      install:
        - pip3 install -r docs/requirements.txt
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
        - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
        - make docs
        - cd ${TRAVIS_BUILD_DIR}
      deploy:
        edge: true
        provider: pages:git
        local_dir: ./build/docs/sphinx
        token: $GITHUB_TOKEN
        verbose: true
